#### Get Orders
GET http://localhost:4004/odata/v4/manage-orders/Orders


##### Get order
GET http://localhost:4004/odata/v4/manage-orders/Orders('client2@client2.com')


### Create Order
POST http://localhost:4004/odata/v4/manage-orders/Orders HTTP/1.1
Content-Type: application/json

{
   "ClientEmail":"client5@client5.com",
   "FirstName":"Lorena",
   "LastName":"Garcia",
   "CreatedOn":"2024-10-10"

}

###### UPDATE ORDER
PUT http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com') HTTP/1.1
Content-Type: application/json

{
    "FirstName": "NewName" ,
    "LastName": "NewLastName"
}

###### DELETE ORDER
DELETE http://localhost:4004/odata/v4/manage-orders/Orders('client5@client5.com') 


###### Get Customer Rate - Function
GET http://localhost:4004/odata/v4/manage-orders/Orders('client2@client2.com')/ManageOrders.getClientTaxRate(clientEmail= 'client2@client2.com') 

###### Cancel Order - Action
POST http://localhost:4004/odata/v4/manage-orders/Orders('client2@client2.com')/ManageOrders.cancelOrder 
Content-Type: application/json

{"clientEmail":"client2@client2.com"}